
#2、编写数据库基本信息
db_1: #数据库1
  db_host: "211.103.136.242"
  db_user: "test"
  db_password: "test123456"
  db_name: "meiduo"
  db_charset: "utf-8"
  db_port: "7090"


db_2: #数据库2
  db_host: "222.103.136.242"
  db_user: "test"
  db_password: "test123456"
  db_name: "meiduo"
  db_charset: "utf-8"
  db_port: "7090"

db_3: #数据库3
  db_host: "233.103.136.242"
  db_user: "test"
  db_password: "test123456"
  db_name: "meiduo"
  db_charset: "utf-8"
  db_port: "7090"

























